accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView


urlpatterns = [

     # accounts
    path('accounts', views.accounts, name='accounts'),
    
     #address
    path('accounts/address', views.accounts_address, name='address'),
    path('accounts/accounts/address/add/<int:typenum>',
         views.accounts_address_add, name='address_add'),
    path('accounts/accounts/address/edit/<int:nid>',
         views.accounts_address_edit, name='address_edit'),
    path('accounts/accounts/address/delete/<int:nid>',
         views.accounts_address_delete, name='address_delete'),
     #login
    path('accounts/register', views.accounts_register, name='register'),
    path('accounts/login', views.accounts_login, name='login'),
    path('accounts/logout', views.accounts_logout, name='logout'),
    path('accounts/reset', views.accounts_reset, name='reset'),


     path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),



     #membership
     path('accounts/membership',views.accounts_membership,name='membership'),
    
]

apis/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router=routers.DefaultRouter()
router.register(r'users',views.UserList,'user')
router.register(r'orders',views.OrderList,'orders')
urlpatterns = [
    path('apis/',include(router.urls)),
]


# urlpatterns = [
#     path('apis/users/<str:userid>', views.users),
#     path('apis/users/',views.users),
#     path('apis/orders/<str:orderid>', views.orders),
#     path('apis/orders/',views.orders),
#     path('apis/products/<str:productid>', views.products),
#     path('apis/products/',views.products),


# ]

yummyyummy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('pages.urls')),
    path('',include('products.urls')),
    path('',include('orders.urls')),
    path('',include('apis.urls')),
    path('',include('accounts.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns+=[path("__reload__/", include("django_browser_reload.urls"))]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.utils.translation import ugettext as _
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import RegexValidator
from django.core.mail import send_mail

# Create your models here.


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(_("first name"), max_length=30)
    last_name = models.CharField(_("last name"), max_length=30)

    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)
    is_active = models.BooleanField(_("active"), default=True)
    avatar = models.ImageField(
        upload_to='avatars/', null=True, blank=True, default="avatars/defaulticon.jpeg")
    is_staff = models.BooleanField(_("is staff"), default=False)
    gender_choices = ((1, 'Male'), (2, 'Female'))
    gender = models.IntegerField(
        _("gender"), choices=gender_choices, null=True)
    age = models.IntegerField(validators=[MaxValueValidator(
        100), MinValueValidator(15)], blank=True, null=True)
    membership = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=True)
    phone = models.CharField(max_length=10, null=True, validators=[
                             RegexValidator('^\d+$', '請輸入數字')])

    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, messgae, form_email=None, **kwargs):
        send_mail(subject, messgae, form_email, [self.email], **kwargs)

    def ordercount(self):
        allordertotal = 0
        for obj in self.order_set.filter(cartcomplete=True):
            allordertotal += float(obj.total or 0)

        # ,self.order_set.filter(cartcomplete=True).aggregate(Sum("total"))
        return self.order_set.filter(cartcomplete=True).count(), round(allordertotal,2)


class Address(models.Model):
    first_name = models.CharField(_("first_name"), max_length=50, null=True)
    last_name = models.CharField(_("last_name"), max_length=50, null=True)
    phone = models.CharField(_("phone"), max_length=50, validators=[
                             RegexValidator('^\d+$', '請輸入數字')])
    country_or_area = models.CharField(_("國家/地區"), max_length=50)
    street_address_1 = models.CharField(_("區域/地區/街道名稱及號碼"), max_length=50)
    street_address_2 = models.CharField(_("屋苑或大廈/座數/樓層/單位"), max_length=50)
    company_name = models.CharField(
        _("company_name"), max_length=50, null=True, blank=True)
    type_choices = (1, "shipping"), (2, "billing")
    type = models.IntegerField(
        _('類別'), choices=type_choices, null=True, blank=True)
    priority = models.IntegerField(_('優先次序'), blank=True, null=True,)
    user = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return f': {self.get_type_display()} ,priority:{self.priority} '

orders/models.py
from django.db import models
from django.utils.translation import ugettext as _
from accounts.models import User,Address
from products.models import Product
orderstatus_choices = (1, "處理中"), (2, "已發貨"), (3, "已完成")


class Voucher(models.Model):
    name = models.CharField(_("name"), max_length=50)
    code = models.CharField(_("code"), max_length=50)
    discount_value = models.DecimalField(
        _("discount_value"), max_digits=5, decimal_places=2)
    discount_value_type = models.CharField(
        _("discount_value_type"), max_length=50)
    apply_to = models.CharField(_("apply to"), max_length=50)
    end_date = models.DateField(
        _("end_date"), auto_now=False, auto_now_add=False)
    # limit=models.DecimalField(_("limit"), max_digits=5, decimal_places=2)
    start_date = models.DateField(
        _("start date"), auto_now=False, auto_now_add=False)
    usage_limit = models.IntegerField(_("usage limit"))
    used = models.IntegerField(_("used"), default=0)

    def __str__(self):
        return f'{self.name}'



class Order(models.Model):
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)
    created = models.DateTimeField(
        _("created"), auto_now=False, auto_now_add=True)
    last_status_change = models.DateTimeField(
        _("last_status_change"), auto_now=True, auto_now_add=False, blank=True, null=True)
    status = models.IntegerField(
        _("status"), choices=orderstatus_choices, default=1)
    total = models.CharField(_("tatol"), max_length=500,
                             blank=True, null=True, default="0")
    billing_address = models.ForeignKey(Address, null=True, blank=True, related_name='orderbillingaddress', verbose_name=_(
        "billing_address"), on_delete=models.DO_NOTHING)
    shipping_address = models.ForeignKey(Address, related_name='ordershippingaddress', verbose_name=_(
        "shipping_address"), on_delete=models.DO_NOTHING, null=True, blank=True)
    discount_amount = models.DecimalField(
        _("discount_amount"), max_digits=5, decimal_places=2, blank=True, null=True)
    discount_name = models.CharField(
        _("discount_name"), max_length=50, blank=True)
    voucher = models.ForeignKey(Voucher, verbose_name=_(
        "voucher"), on_delete=models.DO_NOTHING, blank=True, null=True)
    transaction_id = models.CharField(
        _("transaction_id"), max_length=50, blank=True)
    paid_time = models.DateTimeField(null=True, blank=True)
    cartcomplete = models.BooleanField(default=False)

    def __str__(self):
        return f'User: {self.user.email} , Order Number:{self.id} ,isCart : {not self.cartcomplete}'

    @property
    def get_cart_total(self):
        orderitems = self.ordereditem_set.all()
        total = sum([item.get_total for item in orderitems])
        if self.user.membership:
            total = round(total*90/100, 2)

        if self.voucher:
            discount_value = self.voucher.discount_value
            total = total*(1-discount_value/100)
            total = round(total, 2)

        return total

    def get_cart_total_oringin(self):
        orderitems = self.ordereditem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_quantity(self):
        orderitems = self.ordereditem_set.all()
        quantity = sum([item.quantity for item in orderitems])
        return quantity

class DeliveryGroup(models.Model):
    order = models.OneToOneField(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    last_updated = models.DateTimeField(
        _("last_updated"), auto_now=False, auto_now_add=False)
    shipping_method_name = models.CharField(
        _("shipping_method_name"), max_length=50)
    shipping_price = models.DecimalField(
        _("shipping_price"), max_digits=5, decimal_places=2)
    status = models.CharField(_("status"), max_length=50)
    tracking_number = models.CharField(_("tracking_number"), max_length=50)

    def __str__(self):
        return f'{self.tracking_number}'

class OrderedItem(models.Model):
    product = models.ForeignKey(Product, verbose_name=_(
        "product"), on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(_("quantity"), default=0)
    product_name = models.CharField(
        _("product_name"), max_length=50, null=True, blank=True)
    stock_location = models.CharField(
        _("stock_location"), max_length=50, null=True, blank=True)
    unit_price_gross = models.DecimalField(
        _("unit_price_gross"), max_digits=5, decimal_places=2, null=True, blank=True)
    unit_price_net = models.DecimalField(
        _("unit_price_net"), max_digits=5, decimal_places=2, null=True, blank=True)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    # stock=models.ForeignKey(Stock, verbose_name=_("stock"), on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.id}'

    @property 
    def get_total(self):
        if self.product.sale.all():
            salepricedict = {}
            for obj in self.product.sale.all():
                salepricedict[obj.name] = obj.value
            if self.product.product_class.sale:
                salepricedict[self.product.product_class.sale.name] = self.product.product_class.sale.value
            saleprice = self.product.price
            for key, value in salepricedict.items():
                saleprice *= (1-value/100)
            saleprice = round(saleprice, 2)
            total = self.quantity * saleprice
        else:
            total = self.quantity * self.product.price
        return total

    def get_one_price(self):
        if self.product.sale.all():
            salepricedict = {}
            for obj in self.product.sale.all():
                salepricedict[obj.name] = obj.value
            if self.product.product_class.sale:
                salepricedict[self.product.product_class.sale.name] = self.product.product_class.sale.value
            saleprice = self.product.price
            for key, value in salepricedict.items():
                saleprice *= (1-value/100)
            saleprice = round(saleprice, 2)
            total = saleprice
        else:
            total = self.product.price
        return total

class OrderHistoryEntry(models.Model):
    comment = models.CharField(_("comment"), max_length=50)
    date = models.DateTimeField(_("date"), auto_now=False, auto_now_add=False)
    status = models.CharField(_("status"), max_length=50)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)

class OrderNote(models.Model):
    content = models.CharField(_("content"), max_length=50)
    date = models.DateTimeField(_("date"), auto_now=False, auto_now_add=False)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)

rating_choices=(1,1),(2,2),(3,3),(4,4),(5,5)
class OrderItemsComment(models.Model):
    comment = models.TextField()
    rating = models.IntegerField(choices=rating_choices)
    comment_day = models.DateTimeField(auto_now=True)
    order_items = models.ForeignKey(
        OrderedItem, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return f'Order_items_comment_id:{self.id} ,Order items : {self.order_items} '

templates/accounts/accounts_orderitemcommentadd.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
      <div class="formalert alert info-box d-none" ></div>
      {% if data_dict %}
      <script>
         function myAlert(status, msg,ms=2500) {
const formalert = document.querySelector('.formalert')
formalert.classList.remove("d-none")
formalert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
formalert.innerHTML = msg
document.querySelector('.backtop').click()
setTimeout(() => {
  formalert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
  formalert.classList.add("d-none")
  formalert.innerHTML = ''
 if( status )location.href="{% url 'accounts_orderitemcomments' nid %}"
}, ms)
}
        myAlert({{data_dict.status}},"{{data_dict.msg}}")
      </script>
      {% endif %}
        <div class="row mb-3">
          <h3>商品評論  </h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
            {% for field in  form %}
            
            {{field.label_tag}} <span style="color: red;">{{field.errors.0}}</span>

            
            {{field}}
            {% endfor %}
            
            <input type='submit' class="loginbtn btn btn-success btn-block mt-4 mb-4" value='Submit'>
            
        </div>
          </form>
        </div>

      </div>
  </div>

    
</div>
<script>
  document.querySelectorAll('input,textarea').forEach(item=>{
    item.required=false
  })
</script>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/accounts/accounts_orderitemcommentedit.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
      <div class="formalert alert info-box d-none" ></div>
      {% if data_dict %}
      <script>
         function myAlert(status, msg,ms=2500) {
const formalert = document.querySelector('.formalert')
formalert.classList.remove("d-none")
formalert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
formalert.innerHTML = msg
document.querySelector('.backtop').click()
setTimeout(() => {
  formalert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
  formalert.classList.add("d-none")
  formalert.innerHTML = ''
 if( status )location.href="{% url 'accounts_orderitemcomments' nid %}"
}, ms)
}
        myAlert({{data_dict.status}},"{{data_dict.msg}}")
      </script>
      {% endif %}
        <div class="row mb-3">
          <h3>商品評論  </h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
            {% for field in  form %}
            
            {{field.label_tag}} <span style="color: red;">{{field.errors.0}}</span>

            
            {{field}}
            {% endfor %}
            
            <input type='submit' class="loginbtn btn btn-success btn-block mt-4 mb-4" value='Submit'>
            
        </div>
          </form>
        </div>

      </div>
  </div>

    
</div>
<script> document.querySelectorAll('input,textarea').forEach(item=>{
  item.required=false
})
</script>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/accounts/accounts_orderitemcomments.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
       
        <div class="row mb-3">
          <h3>商品名稱 : {{nid}}</h3>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">商品評價
                </th>
                <th scope="col">評分</th>
                <th scope="col">評價日期</th>
                <th scope="col">操作
                </th>
                
              </tr>
            </thead>
            {% for obj in queryset %}
            
            
            <tbody>
              <tr>
                <th scope="row"><a href="#">{{obj.comment}}</a></th>
                <td>{{obj.rating}}</td>
                <td>{{obj.comment_day}}</td>
                
                <td><a href={% url  'accounts_orderitemcommentedit' obj.id %}>edit</a>
                    <a href={% url  'accounts_orderitemcommentdelete' obj.id %}>delete</a></td>
              </tr>
            </tbody>
             {% endfor %}</table>
        </div>

      </div>
  </div>

    
</div>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/accounts/address_add.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
      <div class="formalert alert info-box d-none" ></div>
      {% if data_dict %}
      <script>
         function myAlert(status, msg,ms=2500) {
const formalert = document.querySelector('.formalert')
formalert.classList.remove("d-none")
formalert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
formalert.innerHTML = msg
document.querySelector('.backtop').click()
setTimeout(() => {
  formalert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
  formalert.classList.add("d-none")
  formalert.innerHTML = ''
 if( status )location.href="{% url 'address' %}"
}, ms)
}
        myAlert({{data_dict.status}},"{{data_dict.msg}}")
      </script>
      {% endif %}
        <div class="row mb-3">
          <h3>新增{% if typenum == 1 %}送貨{% else %}帳單{% endif %}地址 </h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
            {% for field in  form %}
            
            {{field.label_tag}} <span style="color: red;">{{field.errors.0}}</span>
            
            {{field}}
            {% endfor %}
            
            <input type='submit' class="loginbtn btn btn-success btn-block mt-4 mb-4" value='Submit'>
            
        </div>
          </form>
        </div>

      </div>
  </div>

    
</div>
<script>
   document.querySelectorAll('input').forEach(item=>{
    item.required=false
  })
</script>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/accounts/address_edit.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
      <div class="formalert alert info-box d-none" ></div>
      {% if data_dict %}
      <script>
         function myAlert(status, msg,ms=2500) {
const formalert = document.querySelector('.formalert')
formalert.classList.remove("d-none")
formalert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
formalert.innerHTML = msg
document.querySelector('.backtop').click()
setTimeout(() => {
  formalert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
  formalert.classList.add("d-none")
  formalert.innerHTML = ''
 if( status )location.href="{% url 'address' %}"
}, ms)
}
        myAlert({{data_dict.status}},"{{data_dict.msg}}")
      </script>
      {% endif %}
        <div class="row mb-3">
          <h3>地址更改  </h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
            {% for field in  form %}
           
            {{field.label_tag}} <span style="color: red;">{{field.errors.0}}</span>
            
            {{field}}
            {% endfor %}
            
            <input type='submit' class="loginbtn btn btn-success btn-block mt-4 mb-4" value='Submit'>
            
        </div>
          </form>
        </div>

      </div>
  </div>

    
</div>
<script> document.querySelectorAll('input').forEach(item=>{
  item.required=false
})</script>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/accounts/login.html
{% extends "base.html" %} {% block content %}
<section>
  <div class="container" style="width: 27%">
    <h1 class="p-4 text-center">Login</h1>

    <div class="alert info-box"></div>
    <form method="post" id="form">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {% if field.name == 'file' %}
        <div class="custom-file"><input type="file" class="custom-file-input" id='custom'><label for="" class="custom-file-label"></label></div>
        
        {% else %}<label for="{{field.name}}">{{field.label}}</label>
        {{field}}
      </div>{% endif %}{% endfor %}
      
      <button class="loginbtn btn btn-success btn-block mt-4 mb-4">Submit</button>
      <p class="text-center"><a href={% url "register" %}>Create account</a>  /  <a href={% url "password_reset" %}>   Fogot password</a></p>
      <p class="text-center"></p>
    </form>
    {% comment %} <form method="post" id="form">
      {% csrf_token %}
      <div class="form-group">
        <label for="email">Email</label>
        <input
          name="email"
          type="email"
          class="form-control form-control-lg"
          id="email"
          placeholder="enter email" 
          required
          />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          name="password"
          type="password"
          class="form-control form-control-lg"
          id="password"
          placeholder="enter password"
          required />
      </div>
      <button class="loginbtn btn btn-success btn-block mt-4 mb-4">Submit</button>
      <p class="text-center"><a href="">Create account</a></p>
    </form> {% endcomment %}
  </div>
</section>

{% endblock content %} {% block js %}
{% include "formvalidationjs.html" %}
{% endblock js %}

templates/accounts/register.html
{% extends "base.html" %} {% block content %}


<section>
    <div class="container" style="width: 27%;">
          <h1  class='p-4 text-center'>Register</h1>
          
          <div class="alert info-box"></div>
          {% if data_dict %}
          <script>
             function myAlert(status, msg,ms=2500) {
    const alert = document.querySelector('.alert')
    alert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
    alert.innerHTML = msg
    document.querySelector('.backtop').click()
    setTimeout(() => {
      alert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
      alert.innerHTML = ''
     if( status )location.href="/"
    }, ms)
  }
            myAlert({{data_dict.status}},"{{data_dict.msg}}")
          </script>
          {% endif %}
        <form method="post" id='form' enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}<div class="form-group"> 
           {{field.label_tag}}<span style="color: red;">{{field.errors.0}}</span>
            {{field}}
        </div>{% endfor %}


        {{ formset.management_form }}
          {% for form in formset %}
          {% if forloop.counter == 1 %}
          <h3>Default Shipping Address:</h3>
         <input type="checkbox"  id="usesameinfos"><label for="usesameinfos">Use Register User Infomation</label>
         <br>
            {% else %}

            <h3>Default Billing Address:</h3>
          <input type="checkbox" name="usesameaddress" id="usesameaddress" value="1" >
          <label for="usesameaddress">Same as Shipping Address</label>
          <br>
          <input type="checkbox"  id="usesameinfob"><label for="usesameinfob">Use Register User Infomation</label>
         {% endif %}
         {% for field in form %}
         {% if field.name != "id" %}
         <div class="form-group"> 
         {{field.label_tag}}<span style="color: red;">{{field.errors.0}}</span>
          {{field}}
        </div>{% endif %}
          {% endfor %}
          {% endfor %}
          <input type='submit' class="regbtn btn btn-success btn-block mt-4 mb-4" value="Create account">
          <p class="text-center"><a href={%url "login" %}>Login Account</a></p>

        
        </form>
      </div>
    
  </section>

   
  
{% endblock content %}
{% block js %}
<script>

  document.querySelectorAll('#usesameinfos,#usesameinfob').forEach((item,index)=>{item.addEventListener('change',function(){
    document.querySelector(`#id_form-${index}-first_name`).value=''
    document.querySelector(`#id_form-${index}-last_name`).value=''
    document.querySelector(`#id_form-${index}-phone`).value=''
    if(this.checked){
    document.querySelector(`#id_form-${index}-first_name`).value=document.querySelector('#id_first_name').value
    document.querySelector(`#id_form-${index}-last_name`).value=document.querySelector('#id_last_name').value
    document.querySelector(`#id_form-${index}-phone`).value=document.querySelector('#id_phone').value
    }})})

    document.querySelector('#usesameaddress').addEventListener('change',function(){
        const addressTagName=["first_name","last_name","phone","country_or_area","street_address_1","street_address_2","company_name"]
        
        
        addressTagName.forEach(item=>{
          document.querySelector(`#id_form-1-${item}`).value=""
        })
        if(this.checked){
        addressTagName.forEach(item=>{
          document.querySelector(`#id_form-1-${item}`).value=document.querySelector(`#id_form-0-${item}`).value
        })}
        

    })
    document.querySelectorAll('input').forEach(item=>{
      item.required=false
    })
 
</script>
<script>
  function myAlert(status, msg,ms=2500) {
    const alert = document.querySelector('.alert')
    alert.classList.add(status ? 'alert-success' : 'alert-danger', 'show')
    alert.innerHTML = msg
    document.querySelector('.backtop').click()
    setTimeout(() => {
      alert.classList.remove(status ? 'alert-success' : 'alert-danger', 'show')
      alert.innerHTML = ''
     if( status )location.href="/"
    }, ms)
  }
  {% comment %} 
  domform = document.querySelector('#form')
    document.querySelector('.regbtn').addEventListener('click', async e => {
      e.preventDefault()
      const data = new FormData(domform)
      try{const res = await axios({ url: '/accounts/register', method: 'post', data }
      )
      myAlert(res.data.status, res.data.msg )}catch(error){
        document.querySelector('#form').innerHTML=error.response.data
        document.querySelector('.backtop').click()
        const domeve=document.createEvent('Event')
        domeve.initEvent('DOMContentLoaded',true,true)
        document.dispatchEvent(domeve)

      }
    })
  

document.querySelector('#id_avatar').addEventListener('change',e=>{


}){% endcomment %}
</script>  
{% endblock js %}