apis/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router=routers.DefaultRouter()
router.register(r'users',views.UserList,'user')
router.register(r'orders',views.OrderList,'orders')
urlpatterns = [
    path('apis/',include(router.urls)),
]


# urlpatterns = [
#     path('apis/users/<str:userid>', views.users),
#     path('apis/users/',views.users),
#     path('apis/orders/<str:orderid>', views.orders),
#     path('apis/orders/',views.orders),
#     path('apis/products/<str:productid>', views.products),
#     path('apis/products/',views.products),


# ]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #order
    path('orders', views.accounts_orders, name='orders'),
    path('orders/<int:nid>', views.accounts_order, name='order'),
    
    # orderitemscomment part
    path('orders/items/comments/<int:nid>',
         views.accounts_orderitemcomments, name='accounts_orderitemcomments'),
    path('orders/items/comments/add/<int:nid>',
         views.accounts_orderitemcommentadd, name='accounts_orderitemcommentadd'),
    path('orders/items/comments/edit/<int:nid>',
         views.accounts_orderitemcommentedit, name='accounts_orderitemcommentedit'),
    path('orders/items/comments/delete/<int:nid>',
         views.accounts_orderitemcommentdelete, name='accounts_orderitemcommentdelete'),

]

yummyyummy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('pages.urls')),
    path('',include('products.urls')),
    path('',include('orders.urls')),
    path('',include('apis.urls')),
    path('',include('accounts.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns+=[path("__reload__/", include("django_browser_reload.urls"))]

orders/models.py
from django.db import models
from django.utils.translation import ugettext as _
from accounts.models import User,Address
from products.models import Product
orderstatus_choices = (1, "處理中"), (2, "已發貨"), (3, "已完成")


class Voucher(models.Model):
    name = models.CharField(_("name"), max_length=50)
    code = models.CharField(_("code"), max_length=50)
    discount_value = models.DecimalField(
        _("discount_value"), max_digits=5, decimal_places=2)
    discount_value_type = models.CharField(
        _("discount_value_type"), max_length=50)
    apply_to = models.CharField(_("apply to"), max_length=50)
    end_date = models.DateField(
        _("end_date"), auto_now=False, auto_now_add=False)
    # limit=models.DecimalField(_("limit"), max_digits=5, decimal_places=2)
    start_date = models.DateField(
        _("start date"), auto_now=False, auto_now_add=False)
    usage_limit = models.IntegerField(_("usage limit"))
    used = models.IntegerField(_("used"), default=0)

    def __str__(self):
        return f'{self.name}'



class Order(models.Model):
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)
    created = models.DateTimeField(
        _("created"), auto_now=False, auto_now_add=True)
    last_status_change = models.DateTimeField(
        _("last_status_change"), auto_now=True, auto_now_add=False, blank=True, null=True)
    status = models.IntegerField(
        _("status"), choices=orderstatus_choices, default=1)
    total = models.CharField(_("tatol"), max_length=500,
                             blank=True, null=True, default="0")
    billing_address = models.ForeignKey(Address, null=True, blank=True, related_name='orderbillingaddress', verbose_name=_(
        "billing_address"), on_delete=models.DO_NOTHING)
    shipping_address = models.ForeignKey(Address, related_name='ordershippingaddress', verbose_name=_(
        "shipping_address"), on_delete=models.DO_NOTHING, null=True, blank=True)
    discount_amount = models.DecimalField(
        _("discount_amount"), max_digits=5, decimal_places=2, blank=True, null=True)
    discount_name = models.CharField(
        _("discount_name"), max_length=50, blank=True)
    voucher = models.ForeignKey(Voucher, verbose_name=_(
        "voucher"), on_delete=models.DO_NOTHING, blank=True, null=True)
    transaction_id = models.CharField(
        _("transaction_id"), max_length=50, blank=True)
    paid_time = models.DateTimeField(null=True, blank=True)
    cartcomplete = models.BooleanField(default=False)

    def __str__(self):
        return f'User: {self.user.email} , Order Number:{self.id} ,isCart : {not self.cartcomplete}'

    @property
    def get_cart_total(self):
        orderitems = self.ordereditem_set.all()
        total = sum([item.get_total for item in orderitems])
        if self.user.membership:
            total = round(total*90/100, 2)

        if self.voucher:
            discount_value = self.voucher.discount_value
            total = total*(1-discount_value/100)
            total = round(total, 2)

        return total

    def get_cart_total_oringin(self):
        orderitems = self.ordereditem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_quantity(self):
        orderitems = self.ordereditem_set.all()
        quantity = sum([item.quantity for item in orderitems])
        return quantity

class DeliveryGroup(models.Model):
    order = models.OneToOneField(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    last_updated = models.DateTimeField(
        _("last_updated"), auto_now=False, auto_now_add=False)
    shipping_method_name = models.CharField(
        _("shipping_method_name"), max_length=50)
    shipping_price = models.DecimalField(
        _("shipping_price"), max_digits=5, decimal_places=2)
    status = models.CharField(_("status"), max_length=50)
    tracking_number = models.CharField(_("tracking_number"), max_length=50)

    def __str__(self):
        return f'{self.tracking_number}'

class OrderedItem(models.Model):
    product = models.ForeignKey(Product, verbose_name=_(
        "product"), on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(_("quantity"), default=0)
    product_name = models.CharField(
        _("product_name"), max_length=50, null=True, blank=True)
    stock_location = models.CharField(
        _("stock_location"), max_length=50, null=True, blank=True)
    unit_price_gross = models.DecimalField(
        _("unit_price_gross"), max_digits=5, decimal_places=2, null=True, blank=True)
    unit_price_net = models.DecimalField(
        _("unit_price_net"), max_digits=5, decimal_places=2, null=True, blank=True)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    # stock=models.ForeignKey(Stock, verbose_name=_("stock"), on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.id}'

    @property 
    def get_total(self):
        if self.product.sale.all():
            salepricedict = {}
            for obj in self.product.sale.all():
                salepricedict[obj.name] = obj.value
            if self.product.product_class.sale:
                salepricedict[self.product.product_class.sale.name] = self.product.product_class.sale.value
            saleprice = self.product.price
            for key, value in salepricedict.items():
                saleprice *= (1-value/100)
            saleprice = round(saleprice, 2)
            total = self.quantity * saleprice
        else:
            total = self.quantity * self.product.price
        return total

    def get_one_price(self):
        if self.product.sale.all():
            salepricedict = {}
            for obj in self.product.sale.all():
                salepricedict[obj.name] = obj.value
            if self.product.product_class.sale:
                salepricedict[self.product.product_class.sale.name] = self.product.product_class.sale.value
            saleprice = self.product.price
            for key, value in salepricedict.items():
                saleprice *= (1-value/100)
            saleprice = round(saleprice, 2)
            total = saleprice
        else:
            total = self.product.price
        return total

class OrderHistoryEntry(models.Model):
    comment = models.CharField(_("comment"), max_length=50)
    date = models.DateTimeField(_("date"), auto_now=False, auto_now_add=False)
    status = models.CharField(_("status"), max_length=50)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)

class OrderNote(models.Model):
    content = models.CharField(_("content"), max_length=50)
    date = models.DateTimeField(_("date"), auto_now=False, auto_now_add=False)
    order = models.ForeignKey(Order, verbose_name=_(
        "order"), on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, verbose_name=_(
        "user"), on_delete=models.DO_NOTHING)

rating_choices=(1,1),(2,2),(3,3),(4,4),(5,5)
class OrderItemsComment(models.Model):
    comment = models.TextField()
    rating = models.IntegerField(choices=rating_choices)
    comment_day = models.DateTimeField(auto_now=True)
    order_items = models.ForeignKey(
        OrderedItem, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return f'Order_items_comment_id:{self.id} ,Order items : {self.order_items} '

orders/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone


from .models import Order,OrderItemsComment
from yummyyummy.utils.viewsclass import Orderitemcommenteditform
# Create your views here.


@login_required
def accounts_orders(request):
    proces_orders = request.user.order_set.filter(
        status__in=[1, 2], cartcomplete=True)
    old_orders = request.user.order_set.filter(status=3)
    context = {'proces_orders': proces_orders, 'old_orders': old_orders}
    return render(request, 'orders/orders.html', context)


@login_required
def accounts_order(request, nid):
    order = Order.objects.filter(id=nid).first()
    context = {'accounts_order': order}
    return render(request, 'orders/order.html', context)


@login_required
def accounts_orderitemcomments(request, nid):
    # nid = ordereditem id

    queryset = OrderItemsComment.objects.filter(order_items=nid)
    context = {'queryset': queryset, "nid": nid}
    return render(request, 'accounts/accounts_orderitemcomments.html', context)


@login_required
def accounts_orderitemcommentadd(request, nid):
    # nid = ordereditem id
    if request.method == "POST":
        form = Orderitemcommenteditform(data=request.POST)
        if form.is_valid():
            # row_object=OrderItemsComment(order_items_id=nid,comment_day=timezone.now(),rating=request.POST.get("rating"),comment=request.POST.get('comment'))
            # row_object.save()
            form.save()
            form.instance.order_items_id = nid
            form.instance.comment_day = timezone.now()
            form.instance.save()
            context = {"form": form, "nid": nid,
                       "data_dict": {"status": 1, "msg": "新增評論成功"}}
            return render(request, 'accounts/accounts_orderitemcommentadd.html', context)

        context = {"form": form, "nid": nid,
                   "data_dict": {"status": 0, "msg": "驗證失敗"}}
        return render(request, 'accounts/accounts_orderitemcommentadd.html', context)
    form = Orderitemcommenteditform()
    return render(request, 'accounts/accounts_orderitemcommentadd.html', {"form": form})


@login_required
def accounts_orderitemcommentedit(request, nid):

    # nid = .OrderItemsComment id
    row_object = OrderItemsComment.objects.get(id=nid)
    order_items_id = row_object.order_items.id
    if request.method == "POST":
        form = Orderitemcommenteditform(instance=row_object, data=request.POST)
        if form.is_valid():
            form.save()
            # return redirect('accounts_orderitemcomments',order_items_id)
            context = {"form": form, "nid": order_items_id,
                       "data_dict": {"status": 1, "msg": "更改成功"}}
            return render(request, 'accounts/accounts_orderitemcommentedit.html', context)

        context = {"form": form, "nid": order_items_id,
                   "data_dict": {"status": 0, "msg": "驗證失敗"}}
        return render(request, 'accounts/accounts_orderitemcommentedit.html', context)

    form = Orderitemcommenteditform(instance=row_object)
    return render(request, 'accounts/accounts_orderitemcommentedit.html', {"form": form})


@login_required
def accounts_orderitemcommentdelete(request, nid):
    # nid = .OrderItemsComment id
    order_items_id = OrderItemsComment.objects.get(
        id=nid).order_items.id
    OrderItemsComment.objects.get(id=nid).delete()
    return redirect('accounts_orderitemcomments', order_items_id)

templates/orders/order.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
       
        <div class="row mb-3">
          <h3>訂單編號 : {{accounts_order.id}}</h3>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">商品名稱
                </th>
                <th scope="col">商品數量
                </th>
                <th scope="col">商品價格</th>
                <th scope="col">評價</th>
              </tr>
            </thead>
            {% for obj in accounts_order.ordereditem_set.all %}
            
            
            <tbody>
              <tr>
		      <th scope="row"><a href="{% url 'product' obj.product.id %}">{{obj.product.name}}</a></th>
                <td>{{obj.quantity}}</td>
                <td>{{obj.product.price}}</td>
                
                <td><a href={% url 'accounts_orderitemcomments' obj.id %}>查看</a><a href={% url  'accounts_orderitemcommentadd' obj.id %}>新增</a></td>
              </tr>
            </tbody>
             {% endfor %}</table>
        </div>

      </div>
  </div>

    
</div>
{% endblock content %}



{% for item in obj.orderitemscomment_set.all %}
                <td>{{item.comment}}</td>
                {% endfor %}

templates/orders/orders.html
{% extends "base.html" %}
{%load static%}
{% block content %}
<div class="container">

    {% include "partial/_leftbar.html" %}
    <div class="col-lg-8">
        <div class="row mb-3">
          <h3>處理中</h3>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">訂單編號
                </th>
                <th scope="col">交易狀態
                </th>
                <th scope="col">購買日期及時間</th>
                <th scope="col">付款總額</th>
              </tr>
            </thead>
            <tbody>
              {% for item in proces_orders %}
              
             
              <tr>
                <th scope="row">{{item.id}}</th>
                <td>{{item.get_status_display}}</td>
                <td>{{item.paid_time}}</td>
                <td>$ {{item.total}}</td>
              </tr> {% endfor %}
              {% if not proces_orders %}
              <tr><th><p>沒有紀錄 ！</p></th></tr>
              {% endif %}
            </tbody>
          </table>
        </div>
        <div class="row mb-3">
          <h3>歷史紀錄</h3>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">訂單編號
                </th>
                <th scope="col">交易狀態
                </th>
                <th scope="col">購買日期及時間</th>
                <th scope="col">付款總額</th>
              </tr>
            </thead>
            {% for obj in old_orders %}
            
            
            <tbody>
              <tr>
                <th scope="row"><a href={%url 'order' obj.id %}>{{obj.id}}</a></th>
                <td>{{obj.get_status_display}}</td>
                <td>{{obj.paid_time}}</td>
                <td>${{obj.total}}</td>
              </tr>
            </tbody>
          {% endfor %}
          {% if not old_orders %}
          <tr><th><p>沒有紀錄 ！</p></th></tr>
          {% endif %}
        </table>
        </div>

      </div>
  </div>

    
</div>
{% endblock content %}